### ISSUE TITLE
Lost item, The slot thing, no idea

### ISSUE THREAD

**Issue by x3Michels** [TheRedBrain/rpg-inventory#11]
So those are my new items after the update
here are the new book after I equipped for the test. so 1 spell book and the fireworks are on my inventory and those are the old inventory after mod was playable on the server.
![image](https://github.com/user-attachments/assets/ef214f6b-f2f8-4bba-8438-43c150121c10)
 and those are the old inventory after mod was playable on the server.![image](https://github.com/user-attachments/assets/1fa9bd66-2edd-434d-b771-6ea5f3254290)
few items was lost the elytras and the charms was the only one my inventory.
my Axe and a Hammer for break 5x5 was replaced for the sword, 1 glove, 1 ring, shoes and the netherite key for blok the doors, it was on leg slot, the slots mod for elytra and charms those items are disable, so the shift+click wont work on those items.
I have a backup of the world atleast haha, but my problem is how those items for 10 more players? haha

**Comment by x3Michels** [comment]
My axe and a hammer for break 5x5 was replaced for the sword, 1 glove, 1 ring, the slots mod for elytra and charms those items are disable, so the shift+click wont work on those items.

**Comment by TheRedBrain** [comment]
are you sure that you have RPG Inventory installed?
because if you did, your inventory screen should look different

more like this:
![new_inventory_screen](https://github.com/user-attachments/assets/75482e82-ed5b-41bb-b560-101b9f08194b)

**Comment by x3Michels** [comment]
let me take a video, I will equip everything without rpg and slot api, then place those mods on client & server, join again.

**Comment by x3Michels** [comment]
Nvm all of the items are there now, seems like I was joining and testing it on creative but Idk how my items wasn't there when I take the picture
no rpg mod
https://github.com/user-attachments/assets/7c24c78d-26c0-406c-9367-b1d4962b37e2
with rpg mod

https://github.com/user-attachments/assets/9c9e712d-0c98-46a7-8fdd-0b5fc88d608c


only the slot for the elytra, key, boots and charms are no there.

**Comment by TheRedBrain** [comment]
can you tell me what mods add the missing slots?

That would help very much in trying to reproduce this issue

**Comment by TheRedBrain** [comment]
The "are_hand_items_restricted_to_item_tags" option in the server config should be set to true. Setting it to false messes with the shift-click functionality

**Comment by x3Michels** [comment]
NVM ON THIS haha ==== the "are_hand_items_restricted_to_item_tags" was on false, ok I setted it to true, and those items that there's no slot aren't going to equip 
"_Also the weapons from the mod "Advanced Netherite" wont equip too on the primary or secondary weapons slots/shield slots, including the Shields from "Paladins & Priest", also the "elytras" with shift+click it was going to equipp on the secondary weapons slots._ " 
------------------------------------------------------
So the mods that the slot aren't there or not working are=
Heavy Key (keys for leg slot)-(Supplementaries Squared) "supplementaries-1.20-2.8.17-fabric" client & server. 
"elytraslot-fabric-6.4.1+1.20.1" - client & server.
all charms - "mythic_charms-1.1.2" -  client & server.
Running Shoes(Artifacts) "artifacts-fabric-9.5.12" - client & server.

**Comment by TheRedBrain** [comment]
when items don't go into a slot, you can add them to the corresponding tag via a datapack

the slots not appearing is a very weird issue, some mods work, some don't
and they don't do the trinket stuff in different ways

**Comment by TheRedBrain** [comment]
Thanks for the detailed information!

I will investigate further

**Comment by x3Michels** [comment]
Awesome work you made mate!, now the slot that wasnt there they're now working!.

> 1 problem there's a few things that was equipped arent there in the slots(found them in the primary shield after checked on creative, then survial...)
> I been cheking with the mouse if the slot open after being in creative gamemode its was my fault

2 problem is, the setting of the controls are being saved or reseted after a update?
![image](https://github.com/user-attachments/assets/b4b15280-659c-4f9d-8769-3ba533f7309b)

**Comment by TheRedBrain** [comment]
Those two controls were renamed.
They should not reset again (unless I rename them again, which I have no plans for)
