### ISSUE TITLE
Crash on Launch, Possible Incompatability with RPG Inventory and Dehydration

### ISSUE THREAD

**Issue by InputandOutput** [TheRedBrain/rpg-inventory#12]
Launching the game with both RPG Inventory and Dehydration mods installed results in a crash, with the log snippet attached. 
[log.txt](https://github.com/user-attachments/files/16322481/log.txt)
Disabling RPG Inventory resolves the issue when the Dehydration mod is installed, and disabling the Dehydration mod also resolves the issue when RPG Inventory is enabled.

**Comment by TheRedBrain** [comment]
okay that is the weirdest mixin I have ever seen

when you shift-click a very specific item out of the crafting result slot in the player inventory, nbt data is attached to the item if the item doesn't have that data

I feel like that should not be done in the quick move method, but in the ItemStack#copy() method or something like that

**Comment by TheRedBrain** [comment]
but I'll try to make my mixin compatible
I'm actively working on the quick moving anyway
