### ISSUE TITLE
Main Hand and offhand not showing rings/glove slot

### ISSUE THREAD

**Issue by x3Michels** [TheRedBrain/rpg-inventory#13]
So yeah, if you're on inventory mode(1,2,3,) (no "sheathe weapons")
the slot items from ring and gloves there will not appear, like blocked those slot area
Untill you change to sheathe weapons it will appear on the inventory like normaly

https://github.com/user-attachments/assets/164e1f00-e340-4223-9f92-73e5e45be351

**Comment by TheRedBrain** [comment]
Yes that is known.

Sheathing a hand disables the corresponding slot and enables the sheathed hand slot. This is much better than having no access to the item when it is sheathed.
The unfortunate side effect is that all slots in the group are disabled (this is just how Trinkets works).

I suggest that you use a data pack and remove all additional hand slots (rings and gloves). RPG Inventory comes with it's own ring and glove slots.
