### ISSUE TITLE
Inability to equip vanilla axe as weapon

### ISSUE THREAD

**Issue by shoverno2** [TheRedBrain/rpg-inventory#18]
Axe is weapon with high attack, slow speed
and something special: it breaks shields, putting them on cooldown.
However, with RPG inventory it's imposible to equip vanilla axe in weapon slot.

Perhaps, it's because mod considers axe as tool..?

I tested mod on 1.20.1, but it might be that in future versions axes aren't equipable in weapon slots, as such issue wasn't mentioned in update logs.

It's still possible to attack with axe, but no way of dual wielding with RPG inventory.

**Comment by TheRedBrain** [comment]
Will be fixed in the next update

In the mean time, you can fix this with a data pack
add the items to the "data/rpginventory/tags/item/attack_items.json" item tag

Thanks for reporting this issue!

**Comment by TheRedBrain** [comment]
Fixed in version 2.2.0
