### ISSUE TITLE
Crash on Startup with Error: "Mixin apply for mod rpginventory failed rpginventory.mixins.json:trinkets.SurvivalTrinketSlotMixin"

### ISSUE THREAD

**Issue by InputandOutput** [TheRedBrain/rpg-inventory#2]
The new rpginventory release, 1.5.1, produces a crash shown in the log file snippet attached. 
[log_2.txt](https://github.com/user-attachments/files/15821093/log_2.txt)

**Comment by TheRedBrain** [comment]
Fixed in version 1.5.2

Thanks for reporting those issues!
It's very much appreciated!
