### ISSUE TITLE
Can't Interact With the World

### ISSUE THREAD

**Issue by marigold-mortician** [TheRedBrain/rpg-inventory#21]
Latest 2.1.0 for 1.21.1

Testing the mod on its own with its dependencies the mod leaves me unable to properly use the hotbar, nothing I scroll to shows up in my hand. I can mine, break, and pick up blocks but can't place anything. 

https://github.com/user-attachments/assets/2cfd1d98-0f16-4459-a195-36008f4b39b4

**Comment by TheRedBrain** [comment]
Hi!

This is working as intended
One of this mods core features is a dedicated hand slot.

The hotbar can be accessed when the hand items are "sheathed", done via hotkey.

**Comment by marigold-mortician** [comment]
Ha! Now I feel silly for not finding this, thanks :D (now that I'm using it Awesome mod btw)
