### ISSUE TITLE
Main Hand/Off Hand Slots Deleting Items

### ISSUE THREAD

**Issue by InputandOutput** [TheRedBrain/rpg-inventory#3]
Hello TheRedBrain, 
I found an issue where it involves the deletion of items in the mainhand/offhand slots and the sheathing mechanic. 

When sheathing both mainhand and offhand items, the offhand item is deleted, but the main hand item remains. When the mainhand item is sheathed, but I put another item onto the mainhand slot. The sheathed item is deleted and the placed item is used as a new mainhand weapon. 

EDIT: I also noticed that, when pressing the two-handed key while my weapons are sheathed. The message that "Your weapons are sheathed already" appears, but the toggle still goes through - spends stamina and toggles the two-handed stance.

**Comment by mithun0n** [comment]
I don't know if I should open a whole different issue, or just add to this one, as it's directly related. It also **duplicates** items through the same exact feature at times.

**Comment by TheRedBrain** [comment]
One issue is fine. As long as I'm aware of a problem, I don't care in how many or few issues or other ways of communication I learned of the problem ^^

Also, these issues are all related, so it actually makes sense to have them in one place

**Comment by TheRedBrain** [comment]
When exactly does the duplication happen?

**Comment by mithun0n** [comment]
It happened to me while playing around in both creative and survival mode, and putting an iron sword into the weapon slots in the inventory, eventually it would just duplicate sometimes, or get deleted.

**Comment by TheRedBrain** [comment]
okay, I'll see if I can reproduce the duplication glitch

I have an idea how to fix the item deletion, maybe the duplication gets fixed along the way ^^

**Comment by TheRedBrain** [comment]
> EDIT: I also noticed that, when pressing the two-handed key while my weapons are sheathed. The message that "Your weapons are sheathed already" appears, but the toggle still goes through - spends stamina and toggles the two-handed stance.

I can't reproduce it, it works fine for me
If it keeps happening, please open a new issue :)

**Comment by InputandOutput** [comment]
> > EDIT: I also noticed that, when pressing the two-handed key while my weapons are sheathed. The message that "Your weapons are sheathed already" appears, but the toggle still goes through - spends stamina and toggles the two-handed stance.
> 
> I can't reproduce it, it works fine for me If it keeps happening, please open a new issue :)

Nevermind about that issue; I guess I misinterpreted.
