### ISSUE TITLE
Two-Handed Stance Not Saved When Resheathing

### ISSUE THREAD

**Issue by InputandOutput** [TheRedBrain/rpg-inventory#5]
When toggling two-handed stance with a two-handed weapon and unsheathing, resheathing defaults to one-handed stance and makes the two-handed weapon unable to swing (until the two-handed stance is toggled), making quickly switching to a two-handed weapon and attacking cumbersome.

**Comment by TheRedBrain** [comment]
Dark Souls 1 was a big inspiration for this feature and I designed it to be as faithful as possible.

Toggling the 2-handed stance simply sheathes the offhand, so there is currently no way to know if 2-handed stance was active before sheathing.

A possible solution would be to allow toggling 2-handed while both hands are sheathed. So the "Your weapons are sheathed already" message would no longer displayed and your main hand would be unsheathed.
Any thoughts on this?

**Comment by InputandOutput** [comment]
Seems good, though I would like some sort of indication that a two-handed stance is toggled.

**Comment by TheRedBrain** [comment]
Yeah I haven't found an indication I'm satisfied with

When using "Better Combat Extension" a "two_handed_pose" can be defined, which is used when the offhand is empty.

But a HUD element might be necessary.

What kind of indicator would you like to see?
