### ISSUE TITLE
Main hand items

### ISSUE THREAD

**Issue by Aabaddon** [TheRedBrain/rpg-inventory#6]
you should allow us to equip any tool in the main hand, for some reason i cant equip modded weapons in any of the 2 slots and i cant use them

**Comment by TheRedBrain** [comment]
Those slots are technically Trinket slots, which means they can by default only hold items in a certain item tag.

But there is a way to allow all items. And I agree, it would make sense to exactly that to replicate vanilla behaviour.

Will be done in the next update! :)
