### ISSUE TITLE
Inserting an Item Onto an Offhand Slot with a Two-Handed Weapon on Main Hand, Then Unsheathing, Deletes the Offhand Item

### ISSUE THREAD

**Issue by InputandOutput** [TheRedBrain/rpg-inventory#9]
Equiping a two-handed weapon onto the mainhand and an offhand item deletes the offhand item after unsheathing. Should there be a forced unequip/drop of the offhand item when unsheathing/unequiping (or some other solution that doesn't involve losing a precious item)?

**Comment by TheRedBrain** [comment]
What kind of two-handed weapon are you talking about?

is it in the "two_handed_items" item tag?

or is the "two_handed" field in the weapon_attribute file set to true?

**Comment by InputandOutput** [comment]
It is kinda a bit of both: the two-handed tag applied to a weapon (i.e. an arcane staff) versus two-handed weapons that I haven't edited (i.e. simply sword's katanas). Note that "are_hand_items_restricted_to_item_tags" is set to false.

**Comment by TheRedBrain** [comment]
when do items get deleted?
When you equip the arcane staff or the katana?

**Comment by Kireandd** [comment]
If the item is two handed and you slot it in the offhand (/shield icon) slot, happens the moment you unsheath

**Comment by Kireandd** [comment]
https://streamable.com/e7cxtx

**Comment by TheRedBrain** [comment]
Two handed weapon getting deleted when in the offhand has happened before.
Like a year ago, where Better Combat interacted with other mods.

I'll investigate, maybe I can fix it on my end or at least find the issue.

Also, are you using Fabric or Forge?
iirc the last time it happened on Forge

**Comment by Kireandd** [comment]
I'm on Fabric

**Comment by TheRedBrain** [comment]
yeah the issue had nothing to do with Better Combat, I basically mixed up two values
it should be fixed now :)

**Comment by Kireandd** [comment]
Awesome, cheers!
